### ISSUE TITLE
Way of running Server-Monitoring-Script outside the Windows server by providing ip, username, password

### ISSUE THREAD

**Issue by click2cloud-apurva** [mfappsandweb/Server-Monitoring-Script#2]
Hello, this is really a good script to get information of Windows Server. But I need to clone this code in a particular windows VM and run  **python3 monitor.py**

Is there any way of getting these information from outside the windows server by just giving its ip address, username, password.
Thanks in advance.

**Comment by mfcodeworks** [comment]
No, the Python script pulls data from the machine it's running on so it needs to be run on the machine it wants to monitor
